### ISSUE TITLE
Error with local deployment of openwhisk

### ISSUE THREAD

**Issue by zak93kost** [kpavel/openwhisk-local#76]
I am having a problem trying to follow the instructions of owl. The issues appears when I am runnig the comand:

wsk action --apihost http://localhost:3000 invoke owl-test -r -p mykey myval

when I am getting this error:

{
    "error": {
        "code": 4767018,
        "error": "The supplied authentication is invalid"
    },
    "message": "GET https://openwhisk.ng.bluemix.net/api/v1/namespaces/_/actions/owl-test Returned HTTP 401 (Unauthorized) --> \"The supplied authentication is invalid\"",
    "name": "OpenWhiskError",
    "statusCode": 401
}

Apart from that when I am trying to use openwhisk on node-red it won't work for any apihost and auth that I am using. I need to mention that I am using openwhisk out of bluemix (with Vagrant) so I suppose that this might be my problem. Any suggestions?

**Comment by glikson** [comment]
Did you try setting OWL_NEXT_OPENWHISK, as mentioned in https://github.com/kpavel/openwhisk-light/blob/master/CONFIG.md ?
